### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by zootedb0t** [zootedb0t/browser-homepage#5]
Add/Remove bookmarks
- [ ] Add [devdocs](https://devdocs.io/)
- [ ] Remove [you](https://you.com/code)
- [ ] Remove [bookwyrm](https://bookwyrm.social/)
- [ ] Remove [mastodon](https://mastodon.social/)
